from enum import Enum

class Mode(Enum):
    NORMAL = 36
    PULSATING_RAINBOW = 37
    PULSATING_RED = 38
    PULSATING_GREEN = 39
    PULSATING_BLUE = 40
    PULSATING_YELLOW = 41
    PULSATING_CYAN = 42
    PULSATING_PURPLE = 43
    PULSATING_WHITE = 44
    PULSATING_RED_GREEN = 45
    PULSATING_RED_BLUE = 46
    PULSATING_GREEN_BLUE = 47
    RAINBOW_STROBE = 48
    RED_STROBE = 49
    GREEN_STROBE = 50
    BLUE_STROBE = 51
    YELLOW_STROBE = 52
    CYAN_STROBE = 53
    PURPLE_STROBE = 54
    WHITE_STROBE = 55
    RAINBOW_JUMPING_CHANGE = 56
    PULSATING_RGB = 57
    RGB_JUMPING_CHANGE = 58